import Image from 'next/image';
import Link from 'next/link';
import { stats, services, processSteps, faqs, serviceAreas, differentiators } from '../data';
import QuoteForm from './QuoteForm';
import CostCalculator from './CostCalculator';
import ClosetEstimator from './ClosetEstimator';
import RecentProjects from './RecentProjects';

export function Stats(){return <section className="statsBand">{stats.map(({value,label,icon:Icon})=><div className="stat" key={value}><Icon size={56}/><div><strong>{value}</strong><span>{label}</span></div></div>)}</section>}
export function ServicesGrid(){const fullImageSlugs=['/services/design-inventory-management','/services/ikea-systems','/process'];return <section className="section" id="services"><h2>OUR SERVICES</h2><p className="sectionSub">Specializing in IKEA solutions for every room in your home.</p><div className="serviceGrid">{services.map(({slug,shortTitle,text,icon:Icon,img})=><Link className="card" href={slug} key={slug}><div className={`cardImage${fullImageSlugs.includes(slug)?' showFullImage':''}`}><Image src={img} alt={shortTitle.replace('\n',' ')} fill /></div><div className="iconBadge"><Icon size={34}/></div><h3>{shortTitle.split('\n').map((t,i)=><span key={i}>{t}{i<shortTitle.split('\n').length-1 && <br/>}</span>)}</h3><p>{text}</p></Link>)}</div></section>}
export function GalleryPreview(){const projects=[
  {img:'/images/recent-projects/robin-kitchen-main.jpg',alt:'Matte black kitchen cabinetry with white subway tile',caption:'Matte black cabinetry paired with white subway tile and warm hardwood floors.'},
  {img:'/images/recent-projects/robin-kitchen-appliance-wall.jpg',alt:'Black pantry cabinetry and stacked appliance wall',caption:'Full-height pantry storage and a streamlined stacked-appliance wall.'},
  {img:'/images/recent-projects/robin-bathroom-double-vanity.jpg',alt:'Green double vanity and black tile shower',caption:'Soft green double vanity, vessel sinks, and a bold black-tile walk-in shower.'},
  {img:'/images/recent-projects/robin-bathroom-accent-vanity.jpg',alt:'Neutral bathroom vanity with warm accent wall',caption:'A neutral vanity, vessel sink, warm accent wall, and glass-enclosed shower.'},
  {img:'/images/recent-projects/laundry-gray-cabinet.jpg',alt:'Laundry room with gray utility cabinetry and sink',caption:'Gray laundry cabinetry with generous work surfaces, a utility sink, and dedicated appliance space.'},
  {img:'/images/recent-projects/primary-bedroom-mirrored-wardrobes.jpg',alt:'Primary bedroom with floor-to-ceiling mirrored wardrobes',caption:'Floor-to-ceiling mirrored wardrobes add generous storage while visually expanding the bedroom.'},
  {img:'/images/recent-projects/closet-office-storage.jpg',alt:'Closet office with shelving desk and tall cabinets',caption:'A compact built-in workspace with open shelving, a desk, and tall concealed storage.'},
  {img:'/images/recent-projects/walkers-kitchen-main.jpg',alt:'Gray kitchen with integrated handles and undercabinet lighting',caption:'Gray flat-panel cabinetry with integrated handles, full-height storage, and undercabinet lighting.'},
  {img:'/images/recent-projects/walkers-kitchen-wide.jpg',alt:'Gray kitchen with integrated handles and stainless refrigerator',caption:'Gray cabinetry with integrated handles, undercabinet lighting, efficient appliance placement, and a clean transition to the adjoining space.'}
];return <section className="section gallery"><h2>RECENT PROJECTS</h2><p className="sectionSub">Beautiful results. Professional installation.</p><RecentProjects projects={projects} /><Link className="smallCta" href="/gallery">VIEW FULL GALLERY</Link></section>}
export function ProcessSection(){return <section className="process"><h2>OUR SIMPLE PROCESS</h2><p>From your IKEA plan to a kitchen you&apos;ll love.</p><div className="steps">{processSteps.map(({title,text,icon:Icon},i)=><span className="stepWrap" key={title}><div><Icon size={42}/><h3>{title.toUpperCase()}</h3><p>{text}</p></div>{i<processSteps.length-1 && <b>&gt;</b>}</span>)}</div><Link className="cta processCta" href="/quote">UPLOAD YOUR KITCHEN PLAN FOR A FREE QUOTE</Link></section>}
export function QuoteSection(){return <section className="quote quoteWithCalculator"><div className="quoteIntro"><h2>GET YOUR FREE QUOTE</h2><p>Upload your IKEA plan and we&apos;ll take it from there.</p><ol><li><b>Upload your plan</b><span>PDF, PNG, JPG, or room photos.</span></li><li><b>Answer a couple questions</b><span>Inventory, closet design, or expedited service.</span></li><li><b>We review & quote</b><span>You receive a clear, no-obligation quote.</span></li><li><b>Schedule installation</b><span>Once approved, we schedule your installation.</span></li></ol></div><QuoteForm /><div className="quoteCalculators"><CostCalculator /><ClosetEstimator /></div></section>}
export function FAQPreview(){return <section className="section faqBlock"><h2>FAQ</h2><div className="faqList">{faqs.slice(0,4).map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div><Link className="smallCta" href="/faq">VIEW ALL FAQS</Link></section>}
export function AreasPreview(){return <section className="section light"><h2>SERVICE AREAS</h2><p className="sectionSub">Serving the Kansas City metro and Lawrence area.</p><div className="areaGrid">{serviceAreas.map(a=><Link href={a.slug} key={a.slug}>{a.city}</Link>)}</div></section>}
export function WhySKI(){return <section className="section light"><h2>WHY CHOOSE SKI?</h2><div className="whyGrid">{differentiators.map(({title,text,icon:Icon})=><article key={title}><Icon size={40}/><h3>{title}</h3><p>{text}</p></article>)}</div></section>}
